modLoader="javafml"
loaderVersion="${loaderVersionRange}"
license="${modLicense}"
[[mods]]
modId="${mod_id}"
version="${modVersion}"
displayName="${modName}"
authors="${modAuthors}"
description='''${modDescription}'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"